name: Dependabot Jira Cleanup

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

jobs:
  call-workflow:
    uses: askyourteam-nz/github-actions/.github/workflows/dependabot-jira-cleanup.yml@main
    secrets: inherit
